# 한글 번역 API

**Loding csv**

In [515]:
import os
import pandas as pd
import re

data_path = '/home/kotech/workspace/SVAMP/data/cv_mawps'
fold_paths = ['fold0', 'fold1', 'fold2', 'fold3', 'fold4']
fold_path = fold_paths[0]
files = ['dev.csv', 'train.csv']
#file_name = files[0]
file_name = files[1]

path = os.path.join(data_path, fold_path, file_name)

In [45]:
def floatToString(inputValue):
    return ('%.15f' % inputValue).rstrip('0').rstrip('.')

def clean_string(floatString):
    return floatString.rstrip('0').rstrip('.')

In [516]:
import re

NUM_PREFIX = '373'

def replace_numstr(s):
    match_list = re.findall('number(\\d+)', s)
    for i, match in enumerate(match_list):
        s = s.replace('number'+match, NUM_PREFIX+match)
    return s

def restore_numstr(s):
    match_list = re.findall(NUM_PREFIX+'(\\d+)', s)
    for i, match in enumerate(match_list):
        s = s.replace(NUM_PREFIX+match, 'number'+match)
    return s
    

In [517]:
df = pd.read_csv(path)

In [518]:
df

Question            Numbers  \
0     Mary is baking a cake . The recipe wants numbe...            8.0 2.0   
1     There are number0 erasers and number1 scissors...  139.0 118.0 131.0   
2     One pencil weighs number0 grams . How much do ...           28.3 5.0   
3     Zoe was unboxing some of her old winter clothe...        8.0 4.0 6.0   
4     Keith grew number0 cantelopes , Fred grew numb...     29.0 16.0 20.0   
...                                                 ...                ...   
1532  A worker at a medical lab is studying blood sa...  2.0 7341.0 4221.0   
1533  Carlos starts with number0 bananas . number1 a...           39.0 3.0   
1534  There are number0 scissors in the drawer . Kei...          54.0 22.0   
1535  In fourth grade there were number0 students at...     35.0 10.0 10.0   
1536  Third - grade students went to a concert in nu...           8.0 45.0   

                         Equation  Answer  \
0               - number0 number1     6.0   
1               + number0 number2   270.0   
2               * number0 number1   141.5   
3     * number0 + number1 number2    80.0   
4     + + number0 number1 number2    65.0   
...                           ...     ...   
1532            - number1 number2  3120.0   
1533            - number0 number1    36.0   
1534            + number0 number1    76.0   
1535  - + number0 number1 number1    35.0   
1536            * number0 number1   360.0   

                                            group_nums  \
0                   [8, 9, 10, 17, 18, 19, 26, 27, 28]   
1           [1, 2, 3, 4, 5, 6, 12, 13, 14, 24, 25, 26]   
2                       [2, 3, 4, 8, 9, 10, 9, 10, 11]   
3     [11, 12, 13, 21, 22, 23, 24, 25, 26, 35, 36, 37]   
4           [1, 2, 3, 6, 7, 8, 14, 15, 16, 23, 24, 25]   
...                                                ...   
1532  [10, 11, 12, 16, 17, 18, 24, 25, 26, 35, 36, 37]   
1533                    [2, 3, 4, 5, 6, 7, 17, 18, 19]   
1534                  [1, 2, 3, 9, 10, 11, 24, 25, 26]   
1535     [4, 5, 6, 16, 17, 18, 20, 21, 22, 35, 36, 37]   
1536                [8, 9, 10, 14, 15, 16, 22, 23, 24]   

                                                   Body  \
0     Mary is baking a cake . The recipe wants numbe...   
1     There are number0 erasers and number1 scissors...   
2                     One pencil weighs number0 grams .   
3     Zoe was unboxing some of her old winter clothe...   
4     Keith grew number0 cantelopes , Fred grew numb...   
...                                                 ...   
1532  A worker at a medical lab is studying blood sa...   
1533  Carlos starts with number0 bananas . number1 a...   
1534  There are number0 scissors in the drawer . Kei...   
1535  In fourth grade there were number0 students at...   
1536  Third - grade students went to a concert in nu...   

                                         Ques_Statement  
0                  How many cups does she need to add ?  
1             How many erasers are now there in total ?  
2                   How much do number1 pencils weigh ?  
3     How many pieces of winter clothing did Zoe hav...  
4          How many cantelopes did they grow in total ?  
...                                                 ...  
1532   How many blood cells were in the second sample ?  
1533            How many bananas does Carlos end with ?  
1534           How many scissors are now there in all ?  
1535  How many students were in fourth grade at the ...  
1536            How many students went to the concert ?  

[1537 rows x 7 columns]

# stanza

https://stanfordnlp.github.io/stanza/  

In [1]:
#!pip install --pre torch -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html
!pip install --pre torch==1.9.0.dev20210526+cu111 -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html

Looking in links: https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html


In [2]:
import stanza

In [3]:
stanza.download('en') # download English model

2021-05-30 22:38:51 INFO: Downloading default packages for language: en (English)...
2021-05-30 22:38:52 INFO: File exists: /home/kotech/stanza_resources/en/default.zip.
2021-05-30 22:38:54 INFO: Finished downloading models and saved to /home/kotech/stanza_resources.


In [4]:
nlp = stanza.Pipeline('en') # initialize English neural pipeline

2021-05-30 22:38:58 INFO: Loading these models for language: en (English):
| Processor | Package   |
-------------------------
| tokenize  | combined  |
| pos       | combined  |
| lemma     | combined  |
| depparse  | combined  |
| sentiment | sstplus   |
| ner       | ontonotes |

2021-05-30 22:38:58 INFO: Use device: gpu
2021-05-30 22:38:58 INFO: Loading: tokenize
2021-05-30 22:39:01 INFO: Loading: pos
2021-05-30 22:39:01 INFO: Loading: lemma
2021-05-30 22:39:01 INFO: Loading: depparse
2021-05-30 22:39:01 INFO: Loading: sentiment
2021-05-30 22:39:01 INFO: Loading: ner
2021-05-30 22:39:02 INFO: Done loading processors!


In [5]:
doc = nlp("Barack Obama was born in Hawaii.") # run annotation over a sentence

/home/kotech/workspace/venv-nl/lib/python3.7/site-packages/torch/nn/functional.py:652: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1260.)
  return torch.max_pool1d(input, kernel_size, stride, padding, dilation, ceil_mode)


In [6]:
print(doc)

[
  [
    {
      "id": 1,
      "text": "Barack",
      "lemma": "Barack",
      "upos": "PROPN",
      "xpos": "NNP",
      "feats": "Number=Sing",
      "head": 4,
      "deprel": "nsubj:pass",
      "misc": "start_char=0|end_char=6",
      "ner": "B-PERSON"
    },
    {
      "id": 2,
      "text": "Obama",
      "lemma": "Obama",
      "upos": "PROPN",
      "xpos": "NNP",
      "feats": "Number=Sing",
      "head": 1,
      "deprel": "flat",
      "misc": "start_char=7|end_char=12",
      "ner": "E-PERSON"
    },
    {
      "id": 3,
      "text": "was",
      "lemma": "be",
      "upos": "AUX",
      "xpos": "VBD",
      "feats": "Mood=Ind|Number=Sing|Person=3|Tense=Past|VerbForm=Fin",
      "head": 4,
      "deprel": "aux:pass",
      "misc": "start_char=13|end_char=16",
      "ner": "O"
    },
    {
      "id": 4,
      "text": "born",
      "lemma": "bear",
      "upos": "VERB",
      "xpos": "VBN",
      "feats": "Tense=Past|VerbForm=Part|Voice=Pass",
      "head": 0,
      

In [7]:
print(doc.entities)

[{
  "text": "Barack Obama",
  "type": "PERSON",
  "start_char": 0,
  "end_char": 12
}, {
  "text": "Hawaii",
  "type": "GPE",
  "start_char": 25,
  "end_char": 31
}]


In [12]:
text = "If Bryan has 56 books in each of his 9 bookshelves , " \
       "how many books does he have in total ?"
doc = nlp(
    text
)


In [13]:
doc

[
  [
    {
      "id": 1,
      "text": "If",
      "lemma": "if",
      "upos": "SCONJ",
      "xpos": "IN",
      "head": 3,
      "deprel": "mark",
      "misc": "start_char=0|end_char=2",
      "ner": "O"
    },
    {
      "id": 2,
      "text": "Bryan",
      "lemma": "Bryan",
      "upos": "PROPN",
      "xpos": "NNP",
      "feats": "Number=Sing",
      "head": 3,
      "deprel": "nsubj",
      "misc": "start_char=3|end_char=8",
      "ner": "S-PERSON"
    },
    {
      "id": 3,
      "text": "has",
      "lemma": "have",
      "upos": "VERB",
      "xpos": "VBZ",
      "feats": "Mood=Ind|Number=Sing|Person=3|Tense=Pres|VerbForm=Fin",
      "head": 18,
      "deprel": "advcl",
      "misc": "start_char=9|end_char=12",
      "ner": "O"
    },
    {
      "id": 4,
      "text": "56",
      "lemma": "56",
      "upos": "NUM",
      "xpos": "CD",
      "feats": "NumType=Card",
      "head": 5,
      "deprel": "nummod",
      "misc": "start_char=13|end_char=15",
      "ner": "S-CA

In [14]:
print(*[f'id: {word.id}\tword: {word.text}\thead id: {word.head}\thead: {sent.words[word.head-1].text if word.head > 0 else "root"}\tdeprel: {word.deprel}' for sent in doc.sentences for word in sent.words], sep='\n')

id: 1	word: If	head id: 3	head: has	deprel: mark
id: 2	word: Bryan	head id: 3	head: has	deprel: nsubj
id: 3	word: has	head id: 18	head: have	deprel: advcl
id: 4	word: 56	head id: 5	head: books	deprel: nummod
id: 5	word: books	head id: 3	head: has	deprel: obj
id: 6	word: in	head id: 7	head: each	deprel: case
id: 7	word: each	head id: 5	head: books	deprel: nmod
id: 8	word: of	head id: 11	head: bookshelves	deprel: case
id: 9	word: his	head id: 11	head: bookshelves	deprel: nmod:poss
id: 10	word: 9	head id: 11	head: bookshelves	deprel: nummod
id: 11	word: bookshelves	head id: 7	head: each	deprel: nmod
id: 12	word: ,	head id: 18	head: have	deprel: punct
id: 13	word: how	head id: 14	head: many	deprel: advmod
id: 14	word: many	head id: 15	head: books	deprel: amod
id: 15	word: books	head id: 18	head: have	deprel: obj
id: 16	word: does	head id: 18	head: have	deprel: aux
id: 17	word: he	head id: 18	head: have	deprel: nsubj
id: 18	word: have	head id: 0	head: root	deprel: root
id: 19	word: in	head 

In [15]:
text

'If Bryan has 56 books in each of his 9 bookshelves , how many books does he have in total ?'

`59/NUM` <== `nummod` == `books/NOUN`

**Associated Noun**

In [29]:
import os

DATA_PATH = '/home/kotech/workspace/Graph2Tree/mawps/data'
file_name = 'mawps_combine.json'
group_name = 'new_MAWPS_processed.json'
file_path = os.path.join(DATA_PATH, file_name)
group_path = os.path.join(DATA_PATH, group_name)

In [30]:
import json
  
# Opening JSON file
with open(file_path) as json_file:
    data = json.load(json_file)

In [31]:
data

[{'new_equation': 'x = 56 * 9',
  'new_text': 'Bryan took a look at his books as well . If Bryan has 56 books in each of his 9 bookshelves , how many books does he have in total ?',
  'norm_mid_equ': 'x = temp_0 * temp_1',
  'mid_op_equ': 'x = temp_0 <OP> temp_1',
  'num_pos': [13, 19],
  'mask_text': 'Bryan took a look at his books as well . If Bryan has temp_0 books in each of his temp_1 bookshelves , how many books does he have in total ?',
  'num_list': [56.0, 9.0],
  'template_equ': 'x = temp_0 * temp_1',
  'norm_op_equ': 'x = temp_0 temp_1 <OP>',
  'iIndex': 3238,
  'post_equ': 'x = temp_0 temp_1 *',
  'lEquations': ['56*9=x'],
  'sQuestion': 'Bryan took a look at his books as well. If Bryan has 56 books in each of his 9 bookshelves, how many books does he have in total?',
  'lSolutions': [504.0],
  'norm_post_equ': 'x = temp_0 temp_1 *'},
 {'new_equation': 'X = ( 27.0 * 16.0 )',
  'new_text': 'For the fifth grade play , the chairs have been put into 27 rows with 16 chairs in eac

In [32]:
import pandas as pd

df = pd.DataFrame(data)

In [37]:
df['iIndex']

0       3238
1       3784
2        285
3       1956
4         73
        ... 
2368    1847
2369    2390
2370    1689
2371    3265
2372    3842
Name: iIndex, Length: 2373, dtype: int64

In [27]:
# Opening JSON file
with open(group_path) as json_file:
    group_data = json.load(json_file)

In [28]:
group_data

[{'id': 1, 'group_num': [12, 13, 14, 18, 19, 20, 27, 28, 29]},
 {'id': 2, 'group_num': [11, 12, 13, 14, 15, 16, 28, 29, 30]},
 {'id': 3, 'group_num': [1, 2, 3, 5, 6, 7, 17, 18, 19, 33, 34, 35]},
 {'id': 4, 'group_num': [1, 2, 3, 12, 13, 14, 34, 35, 36, 34, 35, 36]},
 {'id': 5, 'group_num': [1, 2, 3, 13, 14, 15, 29, 30, 31]},
 {'id': 6, 'group_num': [1, 2, 3, 8, 9, 10, 16, 17, 18, 21, 22, 23]},
 {'id': 7, 'group_num': [1, 2, 3, 14, 15, 16, 25, 26, 27, 28, 29, 30]},
 {'id': 8, 'group_num': [1, 2, 3, 9, 10, 11, 14, 15, 16, 21, 22, 23]},
 {'id': 9, 'group_num': [4, 5, 6, 11, 12, 13, 17, 18, 19, 30, 31, 32]},
 {'id': 10, 'group_num': [1, 2, 3, 5, 6, 7, 16, 17, 18, 16, 17, 18]},
 {'id': 11, 'group_num': [1, 2, 3, 14, 15, 16, 23, 24, 25]},
 {'id': 12, 'group_num': [1, 2, 3, 6, 7, 8, 15, 16, 17, 30, 31, 32]},
 {'id': 13, 'group_num': [9, 10, 11, 14, 15, 16, 23, 24, 25, 36, 37, 38]},
 {'id': 14, 'group_num': [21, 22, 23, 24, 25, 26, 39, 40, 41, 39, 40, 41]},
 {'id': 15, 'group_num': [7, 8, 9, 1

In [42]:
len(data) == len(group_data)

True

In [44]:
for i, question in enumerate(data):
    question['group_num'] = group_data[i]['group_num']

In [45]:
data

[{'new_equation': 'x = 56 * 9',
  'new_text': 'Bryan took a look at his books as well . If Bryan has 56 books in each of his 9 bookshelves , how many books does he have in total ?',
  'norm_mid_equ': 'x = temp_0 * temp_1',
  'mid_op_equ': 'x = temp_0 <OP> temp_1',
  'num_pos': [13, 19],
  'mask_text': 'Bryan took a look at his books as well . If Bryan has temp_0 books in each of his temp_1 bookshelves , how many books does he have in total ?',
  'num_list': [56.0, 9.0],
  'template_equ': 'x = temp_0 * temp_1',
  'norm_op_equ': 'x = temp_0 temp_1 <OP>',
  'iIndex': 3238,
  'post_equ': 'x = temp_0 temp_1 *',
  'lEquations': ['56*9=x'],
  'sQuestion': 'Bryan took a look at his books as well. If Bryan has 56 books in each of his 9 bookshelves, how many books does he have in total?',
  'lSolutions': [504.0],
  'norm_post_equ': 'x = temp_0 temp_1 *',
  'group_num': [12, 13, 14, 18, 19, 20, 27, 28, 29]},
 {'new_equation': 'X = ( 27.0 * 16.0 )',
  'new_text': 'For the fifth grade play , the ch

In [53]:
for i, d in enumerate(data):
    seq = d["new_text"].strip().split(" ")
    #print(seq)
    group_string = [seq[i] for i in d['group_num']]
    print(d['new_text'])
    print(' '.join(group_string))
    print()

Bryan took a look at his books as well . If Bryan has 56 books in each of his 9 bookshelves , how many books does he have in total ?
has 56 books his 9 bookshelves have in total

For the fifth grade play , the chairs have been put into 27 rows with 16 chairs in each row . How many chairs have been put out for the play ?
into 27 rows with 16 chairs for the play

There are 41 short trees and 44 tall trees currently in the park . Park workers will plant 57 short trees today . How many short trees will the park have when the workers are finished ?
are 41 short and 44 tall plant 57 short workers are finished

Conner has 25000 dollars in his bank account . Every month he spends 1500 dollars . He does not add money to the account . How much money will Conner have in his account after 8 months ?
has 25000 dollars spends 1500 dollars after 8 months after 8 months

There are 34 dogwood trees currently in the park . Park workers will plant 49 dogwood trees today . How many dogwood trees will the 

`group_num`은  `token`+`NUM`+`token` 목록과 문장 끝 마지막 3개 `token` 으로 이루어짐

**RoBERTa**

In [1]:
!pip install transformers==3.3.1

In [2]:
import torch.nn as nn
import torch
from transformers import BertModel, BertTokenizer, RobertaModel, RobertaTokenizer
import pdb

class RobertaEncoder(nn.Module):
        def __init__(self, roberta_model = 'roberta-base', device = 'cuda:0', freeze_roberta = False):
                super(RobertaEncoder, self).__init__()
                self.roberta_layer = RobertaModel.from_pretrained(roberta_model)
                self.roberta_tokenizer = RobertaTokenizer.from_pretrained(roberta_model)
                self.device = device

                if freeze_roberta:
                        for p in self.roberta_layer.parameters():
                                p.requires_grad = False

        def robertify_input(self, sentences):
                '''
                Preprocess the input sentences using roberta tokenizer and converts them to a torch tensor containing token ids

                '''
                # Tokenize the input sentences for feeding into RoBERTa
                all_tokens  = [['<s>'] + self.roberta_tokenizer.tokenize(sentence) + ['</s>'] for sentence in sentences]

                index_retrieve = []
                for sent in all_tokens:
                        cur_ls = [1]
                        for j in range(2, len(sent)):
                                if sent[j][0] == '\u0120':
                                        cur_ls.append(j)
                        index_retrieve.append(cur_ls)

                # Pad all the sentences to a maximum length
                input_lengths = [len(tokens) for tokens in all_tokens]
                max_length    = max(input_lengths)
                padded_tokens = [tokens + ['<pad>' for _ in range(max_length - len(tokens))] for tokens in all_tokens]

                # Convert tokens to token ids
                token_ids = torch.tensor([self.roberta_tokenizer.convert_tokens_to_ids(tokens) for tokens in padded_tokens]).to(self.device)

                # Obtain attention masks
                pad_token = self.roberta_tokenizer.convert_tokens_to_ids('<pad>')
                attn_masks = (token_ids != pad_token).long()

                return token_ids, attn_masks, input_lengths, index_retrieve

        def forward(self, sentences):
                '''
                Feed the batch of sentences to a RoBERTa encoder to obtain contextualized representations of each token
                '''
                # Preprocess sentences
                token_ids, attn_masks, input_lengths, index_retrieve = self.robertify_input(sentences)

                # Feed through RoBERTa
                cont_reps, _ = self.roberta_layer(token_ids, attention_mask = attn_masks)

                return cont_reps, input_lengths, token_ids, index_retrieve

In [3]:
def gpu_init_pytorch(gpu_num):
        '''
                Initialize GPU
        '''
        torch.cuda.set_device(int(gpu_num))
        device = torch.device("cuda:{}".format(
                gpu_num) if torch.cuda.is_available() else "cpu")
        return device

In [4]:
device = gpu_init_pytorch(0)
embedding=RobertaEncoder()
embedding.to(device)
embedding.eval()
pass

In [14]:
text = "If Bryan has 56 books in each of his 9 bookshelves , " \
       "how many books does he have in total ?"
contextual_input = [text]
input_seq1, input_len1, token_ids, index_retrieve = embedding(contextual_input)

In [26]:
input_seq1.shape

torch.Size([1, 25, 768])

In [25]:
input_len1[0]

25

In [23]:
print(token_ids.shape)
token_ids

torch.Size([1, 25])


tensor([[    0,  1106,  7573,    34,  4772,  2799,    11,   349,     9,    39,
           361,  2799,  4393,  3677,  2156,   141,   171,  2799,   473,    37,
            33,    11,   746, 17487,     2]], device='cuda:0')

In [24]:
print(len(index_retrieve[0]))
index_retrieve[0]

21


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]

**BERT multilingual(korean)**

In [368]:
import torch.nn as nn
import torch
from transformers import BertModel, BertTokenizer, RobertaModel, RobertaTokenizer
import pdb

class BertEncoder(nn.Module):
        def __init__(self, bert_model = 'bert-base-multilingual-cased',device = 'cuda:0', freeze_bert = False):
                super(BertEncoder, self).__init__()
                self.bert_layer = BertModel.from_pretrained(bert_model)
                self.bert_tokenizer = BertTokenizer.from_pretrained(bert_model)
                self.device = device

                if freeze_bert:
                        for p in self.bert_layer.parameters():
                                p.requires_grad = False

        def bertify_input(self, sentences):
                '''
                Preprocess the input sentences using bert tokenizer and converts them to a torch tensor containing token ids

                '''
                #Tokenize the input sentences for feeding into BERT
                # pdb.set_trace()
                all_tokens  = [['[CLS]'] + self.bert_tokenizer.tokenize(sentence) + ['[SEP]'] for sentence in sentences]

                index_retrieve = []
                for sent in all_tokens:
                        cur_ls = []
                        for j in range(1, len(sent)):
                                if sent[j][0] == '#':
                                        continue
                                else:
                                        cur_ls.append(j)
                        index_retrieve.append(cur_ls)

                #Pad all the sentences to a maximum length
                input_lengths = [len(tokens) for tokens in all_tokens]
                max_length    = max(input_lengths)
                padded_tokens = [tokens + ['[PAD]' for _ in range(max_length - len(tokens))] for tokens in all_tokens]

                #Convert tokens to token ids
                token_ids = torch.tensor([self.bert_tokenizer.convert_tokens_to_ids(tokens) for tokens in padded_tokens]).to(self.device)

                #Obtain attention masks
                pad_token = self.bert_tokenizer.convert_tokens_to_ids('[PAD]')
                attn_masks = (token_ids != pad_token).long()

                return token_ids, attn_masks, input_lengths, index_retrieve

        def forward(self, sentences):
                '''
                Feed the batch of sentences to a BERT encoder to obtain contextualized representations of each token
                '''
                #Preprocess sentences
                token_ids, attn_masks, input_lengths, index_retrieve = self.bertify_input(sentences)

                #Feed through bert
                cont_reps, _ = self.bert_layer(token_ids, attention_mask = attn_masks)

                return cont_reps, input_lengths, token_ids, index_retrieve

In [369]:
def gpu_init_pytorch(gpu_num):
        '''
                Initialize GPU
        '''
        torch.cuda.set_device(int(gpu_num))
        device = torch.device("cuda:{}".format(
                gpu_num) if torch.cuda.is_available() else "cpu")
        return device

device = gpu_init_pytorch(0)
embedding=BertEncoder()
embedding.to(device)
embedding.eval()

BertEncoder(
  (bert_layer): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine

In [370]:
text = "만약 브라이언이 그의 9개의 책꽂이에 56권의 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
text = "만약 철수가 그의 9개의 책꽂이에 56권의 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
text = "만약 민준이 그의 9개의 책꽂이에 56권의 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
text = "서현이 그의 9개의 책꽂이에 56권의 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
contextual_input = [text]
input_seq1, input_len1, token_ids, index_retrieve = embedding(contextual_input)

In [371]:
text = "기차는 3730마리의 개를 기르고 있다."
text = "만약 민준이 그의 9개의 자동차에 56권의 고양이 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
embedding.bert_tokenizer.tokenize(text)

['만',
 '##약',
 '민',
 '##준',
 '##이',
 '그의',
 '9',
 '##개의',
 '자',
 '##동차',
 '##에',
 '56',
 '##권',
 '##의',
 '고',
 '##양',
 '##이',
 '책',
 '##을',
 '가지고',
 '있다',
 '##면',
 ',',
 '그는',
 '총',
 '몇',
 '##권',
 '##의',
 '책',
 '##을',
 '가지고',
 '있는',
 '##가',
 '?']

In [344]:
input_seq1.shape

torch.Size([1, 29, 768])

In [345]:
input_len1[0]

29

In [346]:
print(token_ids.shape)
token_ids

torch.Size([1, 29])


tensor([[  101,  9425, 30842, 10739, 21555,   130, 32501,   100, 11628, 25347,
         10459,  9739, 10622, 44270, 11506, 14867,   117, 17889,  9761,  9282,
         25347, 10459,  9739, 10622, 44270, 13767, 11287,   136,   102]],
       device='cuda:0')

In [347]:
print(len(index_retrieve[0]))
index_retrieve[0]

17


[1, 4, 5, 7, 8, 11, 13, 14, 16, 17, 18, 19, 22, 24, 25, 27, 28]

In [348]:
sentences = contextual_input
tokens  = [['[CLS]'] + embedding.bert_tokenizer.tokenize(sentence) + ['[SEP]'] for sentence in sentences]

In [349]:
' '.join(tokens[0])

'[CLS] 서 ##현 ##이 그의 9 ##개의 [UNK] 56 ##권 ##의 책 ##을 가지고 있다 ##면 , 그는 총 몇 ##권 ##의 책 ##을 가지고 있는 ##가 ? [SEP]'

In [56]:
# token_id로부터 token 구하기
res = embedding.bert_tokenizer.convert_ids_to_tokens(token_ids[0])
' '.join(res)

'[CLS] 만 ##약 철 ##수가 그의 9 ##개의 [UNK] 56 ##권 ##의 책 ##을 가지고 있다 ##면 , 그는 총 몇 ##권 ##의 책 ##을 가지고 있는 ##가 ? [SEP]'

**XMLRoberata multilingual(korean)**

In [378]:
import torch.nn as nn
import torch
from transformers import BertModel, BertTokenizer, RobertaModel, RobertaTokenizer
from transformers import XLMRobertaModel, XLMRobertaTokenizer
import pdb

class XLMRobertaEncoder(nn.Module):
        def __init__(self, roberta_model = 'xlm-roberta-base', device = 'cuda:0', freeze_roberta = False):
                super(XLMRobertaEncoder, self).__init__()
                self.roberta_layer = XLMRobertaModel.from_pretrained(roberta_model)
                self.roberta_tokenizer = XLMRobertaTokenizer.from_pretrained(roberta_model)
                self.device = device

                if freeze_roberta:
                        for p in self.roberta_layer.parameters():
                                p.requires_grad = False

        def robertify_input(self, sentences):
                '''
                Preprocess the input sentences using roberta tokenizer and converts them to a torch tensor containing token ids

                '''
                # Tokenize the input sentences for feeding into RoBERTa
                all_tokens  = [['<s>'] + self.roberta_tokenizer.tokenize(sentence) + ['</s>'] for sentence in sentences]

                index_retrieve = []
                for sent in all_tokens:
                        cur_ls = [1]
                        for j in range(2, len(sent)):
                                if sent[j][0] == '\u0120':
                                        cur_ls.append(j)
                        index_retrieve.append(cur_ls)

                # Pad all the sentences to a maximum length
                input_lengths = [len(tokens) for tokens in all_tokens]
                max_length    = max(input_lengths)
                padded_tokens = [tokens + ['<pad>' for _ in range(max_length - len(tokens))] for tokens in all_tokens]

                # Convert tokens to token ids
                token_ids = torch.tensor([self.roberta_tokenizer.convert_tokens_to_ids(tokens) for tokens in padded_tokens]).to(self.device)

                # Obtain attention masks
                pad_token = self.roberta_tokenizer.convert_tokens_to_ids('<pad>')
                attn_masks = (token_ids != pad_token).long()

                return token_ids, attn_masks, input_lengths, index_retrieve

        def forward(self, sentences):
                '''
                Feed the batch of sentences to a RoBERTa encoder to obtain contextualized representations of each token
                '''
                # Preprocess sentences
                token_ids, attn_masks, input_lengths, index_retrieve = self.robertify_input(sentences)

                # Feed through RoBERTa
                cont_reps, _ = self.roberta_layer(token_ids, attention_mask = attn_masks)

                return cont_reps, input_lengths, token_ids, index_retrieve

In [379]:
def gpu_init_pytorch(gpu_num):
        '''
                Initialize GPU
        '''
        torch.cuda.set_device(int(gpu_num))
        device = torch.device("cuda:{}".format(
                gpu_num) if torch.cuda.is_available() else "cpu")
        return device

device = gpu_init_pytorch(0)
embedding=XLMRobertaEncoder()
embedding.to(device)
embedding.eval()

XLMRobertaEncoder(
  (roberta_layer): XLMRobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(250002, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm):

In [380]:
text = "만약 브라이언이 그의 9개의 책꽂이에 56권의 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
#text = "만약 철수가 그의 9개의 책꽂이에 56권의 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
#text = "만약 민준이 그의 9개의 자동차에 56권의 고양이 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
contextual_input = [text]
input_seq1, input_len1, token_ids, index_retrieve = embedding(contextual_input)

In [381]:
# token_id로부터 token 구하기
res = embedding.roberta_tokenizer.convert_ids_to_tokens(token_ids[0])
' '.join(res)

'<s> ▁만약 ▁브 라이 언 이 ▁그의 ▁9 개의 ▁책 꽂 이 에 ▁56 권 의 ▁책을 ▁가지고 ▁있다면 , ▁그는 ▁총 ▁몇 권 의 ▁책을 ▁가지고 ▁있는 가 ? </s>'

In [386]:
text = '고양이가 야구를 한다'
res = embedding.roberta_tokenizer.tokenize(text)
' '.join(res)

'▁고양이 가 ▁ 야구 를 ▁한다'

**KoBERT**

```bash
sdf
```

In [372]:
from gluonnlp.data import SentencepieceTokenizer
from kobert.utils import get_tokenizer
tok_path = get_tokenizer()

using cached model


In [373]:
sp  = SentencepieceTokenizer(tok_path)

In [72]:
sp('한국어 모델을 공유합니다.')

['▁한국', '어', '▁모델', '을', '▁공유', '합니다', '.']

In [74]:
' '.join(sp(text))

'▁만약 ▁철 수가 ▁그의 ▁9 개의 ▁책 꽂 이 에 ▁ 56 권 의 ▁책 을 ▁가지고 ▁있다 면 , ▁그는 ▁총 ▁몇 권 의 ▁책 을 ▁가지고 ▁있는 가 ?'

sp(text)

결과 comment:   
`_`, `56` 은 문제될 것 같음

In [375]:
text = "만약 민준이 그의 9개의 자동차에 56권의 고양이 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?"
text = '앤더슨은 각각의 페이지에 3730개의 바인더로 그의 야구 카드를 정리하고 있었다. 만약 그가 바인더에 넣을 3731개의 새로운 카드와 3732개의 오래된 카드를 가지고 있다면, 그는 얼마나 많은 페이지를 사용했을까요?'
' '.join(sp(text))

'▁앤 더 슨 은 ▁각각 의 ▁페 이 지 에 ▁37 30 개의 ▁바 인 더 로 ▁그의 ▁야구 ▁카드 를 ▁정리 하고 ▁있었다 . ▁만약 ▁그가 ▁바 인 더 에 ▁넣 을 ▁37 31 개의 ▁새로운 ▁카드 와 ▁37 32 개의 ▁오래 된 ▁카드 를 ▁가지고 ▁있다 면 , ▁그는 ▁얼마나 ▁많은 ▁페 이 지를 ▁사용 했을 까 요 ?'

**KoElectra**

In [387]:
from transformers import AutoTokenizer, AutoModel

In [388]:
tokenizer = AutoTokenizer.from_pretrained("beomi/KcELECTRA-base")

OSError: Can't load config for 'beomi/KcELECTRA-base'. Make sure that:

- 'beomi/KcELECTRA-base' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'beomi/KcELECTRA-base' is the correct path to a directory containing a config.json file



**Stanza extract en names**

In [77]:
import stanza

nlp = stanza.Pipeline(lang='en', processors='tokenize,ner')
doc = nlp("Chris Manning teaches at Stanford University. He lives in the Bay Area.")
print(*[f'entity: {ent.text}\ttype: {ent.type}' for sent in doc.sentences for ent in sent.ents], sep='\n')

2021-06-01 13:40:41 INFO: Loading these models for language: en (English):
| Processor | Package   |
-------------------------
| tokenize  | combined  |
| ner       | ontonotes |

2021-06-01 13:40:41 INFO: Use device: gpu
2021-06-01 13:40:41 INFO: Loading: tokenize
2021-06-01 13:40:41 INFO: Loading: ner
2021-06-01 13:40:42 INFO: Done loading processors!


entity: Chris Manning	type: PERSON
entity: Stanford University	type: ORG
entity: the Bay Area	type: LOC


In [78]:
text = "If Bryan has 56 books in each of his 9 bookshelves , " \
       "how many books does he have in total ?"
doc = nlp(text)
print(*[f'entity: {ent.text}\ttype: {ent.type}' for sent in doc.sentences for ent in sent.ents], sep='\n')

entity: Bryan	type: PERSON
entity: 56	type: CARDINAL
entity: 9	type: CARDINAL


# 번역

In [790]:
import os
import pandas as pd

folder_path = '/home/kotech/workspace/SVAMP/code/graph2tree/data/cv_asdiv-a'
folder_path = '/home/kotech/workspace/SVAMP/code/graph2tree/data/cv_mawps/fold0'
#csv_file = 'dev.csv'
#csv_file = 'train-trans.csv'
#csv_file = 'train.csv'
#csv_file = 'dev-trans.csv'
csv_file = 'dev.csv'

path = os.path.join(folder_path, csv_file)

#df = pd.read_csv(path)
csv_file = 'dev.csv'

In [791]:
kor_path = os.path.splitext(path)[0]+'-ko'+os.path.splitext(path)[1]
trans_path = os.path.splitext(path)[0]+'-trans'+os.path.splitext(path)[1]

In [792]:
kor_path

'/home/kotech/workspace/SVAMP/code/graph2tree/data/cv_mawps/fold0/dev-ko.csv'

In [520]:
for q in df['Question']:
    doc = nlp(q)
    for sent in doc.sentences:
        for ent in sent.ents:
            if ent.type == 'PERSON':
                print(ent.text)

Mary
Jason
Zoe
Zoe
Keith
Fred
Jason
Ashley
Adam
Ann
Ann
Ann
Katie
Katie
Ezra
Lisa
Lisa
Jerry
Kaleb
Nicole
Sam
Sam
Carol
Carol
Hilt
John
Elizabeth
Roden
Sandy
Sandy
Sandy
Sally
Sam
Fred
Keith
Fred
Fred
Lino
Zach
Ben
Zach
Megan
Megan
Betty
Alyssa
Nancy
Alyssa
Nancy
Joe
Daniel
Joe
Patricia
Albert
Patricia
Joyce
Marie
Joyce
Joyce
Joyce
Tammy
Emily
Emily
Edward
Edward
Nancy
Jane ’ s
Jane
Jane
Guzman
Victor
Sally
Mary
Logan
Logan
Benny
Michael
Salesperson
Rosa
Rosa
Jane
Louis
Tom
Tom
Karen
Karen
Justin
Justin
Jane
Sean
Sean
Wendy
Wendy
Marilyn
Daniel
Marilyn
Bryan
Ben
Marta
Joan
Mike
Sam
Mary
Willy
Lucy
Willy
Lucy
Mary
Jason
Hilt
Craig
Craig
Brett
Harold
Steve
Harold
Spencer
Spencer
Jessica
Jessica
Sheridan
Garrett
Garrett
Sheridan
Dan
Sara
Dan
Nancy
Sandy
Mary
Roger
Katie
Katie
Sam
Larry
Larry
Julian
Dan
Jennifer
Jennifer
Olivia
Sally
Tom
Jessica
Diane
Diane
Jerry
Jerry
Melanie
Benny
Paula
Paula
Carol
Victor
Gwen
Sarah
Helen
Ann
Helen
Jeffrey
Jeffrey
Sheridan
Molly
Molly
Jessica
Sandy
Jessi

In [148]:
for q in df['Question']:
    print(q)

gino has number0 popsicle sticks . i have number1 popsicle sticks . what is the sum of our popsicle sticks ?
lino picked up number0 shells at the seashore in the morning and number1 shells in the afternoon . how many shells did he pick up in all ?
there were number0 parents in the program and number1 pupils too . how many people were present in the program ?
last saturday marie sold number0 magazines and number1 newspapers . what is the total number of reading materials she sold ?
there are number0 birds on the fence . number1 more birds land on the fence . how many birds are on the fence ?
number0 boys went down the slide . number1 more boys went down the slide . how many boys went down the slide ?
number0 ducks are swimming in a lake . number1 more ducks come to join them . how many ducks are swimming in the lake ?
number0 dogs are barking . number1 more dogs start to bark . how many dogs are barking ?
bobby ate number0 pieces of candy . then he ate number1 more . how many pieces of 

In [113]:
text = 'Jose has number0 chickens and number1 ducks . how many fowls does he have ?'
text = 'Jovana had number0 pounds of shells in her bucket . she added some shells and now has number1 pounds of shells . how many pounds did she add ?'
doc = nlp(text)

In [114]:
print(*[f'entity: {ent.text}\ttype: {ent.type}' for sent in doc.sentences for ent in sent.ents], sep='\n')

entity: Jovana	type: ORG
entity: number0 pounds	type: QUANTITY
entity: number1 pounds	type: QUANTITY


missing names:  
```
jovana, jose
```

https://stackoverflow.com/questions/20290870/improving-the-extraction-of-human-names-with-nltk  

https://github.com/wolfgangmm/exist-stanford-ner/blob/master/resources/classifiers/english.all.3class.distsim.crf.ser.gz  

https://nlp.stanford.edu/software/CRF-NER.html#Download  



In [95]:
import nltk
from nltk.tag.stanford import StanfordNERTagger

In [96]:
st = StanfordNERTagger('stanford-ner/english.all.3class.distsim.crf.ser.gz',
                       'stanford-ner/stanford-ner-4.2.0.jar')

In [97]:
text = u"""
Some economists have responded positively to Bitcoin, including
Francois R. Velde, senior economist of the Federal Reserve in Chicago
who described it as "an elegant solution to the problem of creating a
digital currency." In November 2013 Richard Branson announced that
Virgin Galactic would accept Bitcoin as payment, saying that he had invested
in Bitcoin and found it "fascinating how a whole new global currency
has been created", encouraging others to also invest in Bitcoin.
Other economists commenting on Bitcoin have been critical.
Economist Paul Krugman has suggested that the structure of the currency
incentivizes hoarding and that its value derives from the expectation that
others will accept it as payment. Economist Larry Summers has expressed
a "wait and see" attitude when it comes to Bitcoin. Nick Colas, a market
strategist for ConvergEx Group, has remarked on the effect of increasing
use of Bitcoin and its restricted supply, noting, "When incremental
adoption meets relatively fixed supply, it should be no surprise that
prices go up. And that’s exactly what is happening to BTC prices.
"""

In [98]:
for sent in nltk.sent_tokenize(text):
    tokens = nltk.tokenize.word_tokenize(sent)
    tags = st.tag(tokens)
    for tag in tags:
        if tag[1] in ["PERSON", "LOCATION", "ORGANIZATION"]:
            print(tag)

('Bitcoin', 'LOCATION')
('Francois', 'PERSON')
('R.', 'PERSON')
('Velde', 'PERSON')
('Federal', 'ORGANIZATION')
('Reserve', 'ORGANIZATION')
('Chicago', 'LOCATION')
('Richard', 'PERSON')
('Branson', 'PERSON')
('Virgin', 'PERSON')
('Galactic', 'PERSON')
('Bitcoin', 'PERSON')
('Bitcoin', 'LOCATION')
('Bitcoin', 'LOCATION')
('Paul', 'PERSON')
('Krugman', 'PERSON')
('Larry', 'PERSON')
('Summers', 'PERSON')
('Bitcoin', 'PERSON')
('Nick', 'PERSON')
('Colas', 'PERSON')
('ConvergEx', 'ORGANIZATION')
('Group', 'ORGANIZATION')
('Bitcoin', 'LOCATION')
('BTC', 'ORGANIZATION')


In [121]:
text = 'Jose has number0 chickens and number1 ducks . You are Jovana'
text = 'jose has number0 chickens and number1 ducks . You are jovana' # NG

In [122]:
for sent in nltk.sent_tokenize(text):
    tokens = nltk.tokenize.word_tokenize(sent)
    tags = st.tag(tokens)
    for tag in tags:
        if tag[1] in ["PERSON", "LOCATION", "ORGANIZATION"]:
            print(tag)

In [538]:
exception_word = ['has', 'have', 'had', 'and', 'brought', 'took', 'the', 'steal', 'wood', 'woods',
                  'Halloween', 'halloween', 'repainted', 'use', 'dad', '’',
                 ]
missing_word = ['hilt', 'blithe', 'christian', 'felton', 'fortree', 'shiela', 'buddy', 'jasmin',
                'charlie', 'dean', 'connie', 'anita', 'savant', 'billy', 'maria', 'tiffany', 'isabel',
               ]
'''
mrs. hilt has $ number0 . she spends $ number1 on a toy truck and $ number2 on a pencil case . how much money does she have left ?

#mawps missing_word
Connie, Eve

’:  tagged as PERSON
672
Mary ’ s mom is getting ready for Mary ’ s birthday party . She blew up number0 balloons this morning and number1 balloons this afternoon . How many balloons did she blow up in all ?
Anderson Cyndia s mom is getting ready for Anderson Cyndia s birthday party . She blew up 3730 balloons this morning and 3731 balloons this afternoon . How many balloons did she blow up in all ?
'''
sometimes_word = [ 'hilt' ]
wrong_tag = [
                #location
                'marin', 'charlotte', 'sofia', 'olivia',
            ]

for q in df['Question']:
    q = replace_numstr(q)
    print(q)
    q_cap = q
    #q_list = q.split(' ')
    #for i, w in enumerate(q_list):
    #    if w not in exception_word:
    #        q_list[i] = w.capitalize()
    #q_cap = ' '.join(q_list)
    tokens = nltk.tokenize.word_tokenize(q_cap)
    tags = st.tag(tokens)
    tag_list = []
    for tag in tags:
        #print(tag[1])
        #if tag[1] in ["PERSON", "LOCATION", "ORGANIZATION"]:
        #if tag[1] in ["PERSON", "LOCATION"]:
        #if tag[1] in ["LOCATION"]:
        if tag[1] in ["PERSON"]:
            tag_list.append(tag)
    if len(tag_list) > 0:
        #print(q)
        print(tag_list)
        print()
    print()

Mary is baking a cake . The recipe wants 3730 cups of flour . She already put in 3731 cups . How many cups does she need to add ?
[('Mary', 'PERSON')]


There are 3730 erasers and 3731 scissors in the drawer . Jason placed 3732 erasers in the drawer . How many erasers are now there in total ?
[('Jason', 'PERSON')]


One pencil weighs 3730 grams . How much do 3731 pencils weigh ?

Zoe was unboxing some of her old winter clothes . She found 3730 boxes of clothing and inside each box there were 3731 scarves and 3732 mittens . How many pieces of winter clothing did Zoe have total ?
[('Zoe', 'PERSON'), ('Zoe', 'PERSON')]


Keith grew 3730 cantelopes , Fred grew 3731 cantelopes , and Jason grew 3732 cantelopes . How many cantelopes did they grow in total ?
[('Keith', 'PERSON'), ('Fred', 'PERSON'), ('Jason', 'PERSON')]


Ashley sold 3730 boxes of Samoas . How many cases of 3731 boxes , plus extra boxes does Ashley need ?


KeyboardInterrupt: 

In [522]:
# Brian ==> 가끔 번역안됨
en_names = ['Anderson', 'Cyndia', 'Fred', 'Wendy', 'Angela', 'Robert', 'Steven']
ko_names = ['앤더슨', '신디아', '프레드', '웬디', '안젤라', '로버트', '스티븐']

**주의**

In [525]:
# column 추가, 삭제
import numpy as np

if 'q_conv' not in df.columns:
    df['q_conv'] = np.nan
if 'q_papago' not in df.columns:
    df['q_papago'] = np.nan
if 'q_ko' not in df.columns:
    df['q_ko'] = np.nan
if 'group_nums_ko' not in df.columns:
    df['group_nums_ko'] = np.nan

#df.drop('q_papgo', axis=1, inplace=True)
#df.drop('group_num_ko', axis=1, inplace=True)

In [793]:
df

Question  \
0    Bryan took a look at his books as well . If Br...   
1    For the fifth grade play , the chairs have bee...   
2    There are number0 short trees and number1 tall...   
3    Conner has number0 dollars in his bank account...   
4    There are number0 dogwood trees currently in t...   
..                                                 ...   
379  There are number0 pencils and number1 crayons ...   
380  There are number0 pencils in the drawer . Sara...   
381  During a school play , Jonah staffed the snack...   
382  I have a pet golden retriever . Each year he g...   
383  Kaleb had saved up number0 dollars . If he rec...   

                          Numbers                     Equation        Answer  \
0                        56.0 9.0            * number0 number1    504.000000   
1                       27.0 16.0            * number0 number1    432.000000   
2                  41.0 44.0 57.0            + number0 number2     98.000000   
3              25000.0 1500.0 8.0  - number0 * number1 number2  13000.000000   
4                       34.0 49.0            + number0 number1     83.000000   
..                            ...                          ...           ...   
379                34.0 49.0 22.0            - number0 number2     12.000000   
380                   115.0 100.0            + number0 number1    215.000000   
381  0.25 0.4166666666666667 0.25  + + number0 number0 number1      0.916667   
382                      11.0 8.0            * number0 number1     88.000000   
383                 21.0 15.0 6.0  / + number0 number1 number2      6.000000   

                                           group_nums  \
0                [12, 13, 14, 18, 19, 20, 27, 28, 29]   
1                [11, 12, 13, 14, 15, 16, 28, 29, 30]   
2          [1, 2, 3, 5, 6, 7, 17, 18, 19, 33, 34, 35]   
3       [1, 2, 3, 12, 13, 14, 34, 35, 36, 34, 35, 36]   
4                   [1, 2, 3, 13, 14, 15, 29, 30, 31]   
..                                                ...   
379        [1, 2, 3, 4, 5, 6, 12, 13, 14, 24, 25, 26]   
380                  [1, 2, 3, 9, 10, 11, 24, 25, 26]   
381  [12, 13, 14, 21, 22, 23, 28, 29, 30, 42, 43, 44]   
382              [10, 11, 12, 15, 16, 17, 23, 24, 25]   
383     [3, 4, 5, 10, 11, 12, 18, 19, 20, 22, 23, 24]   

                                                  Body  \
0    Bryan took a look at his books as well . If Br...   
1    For the fifth grade play , the chairs have bee...   
2    There are number0 short trees and number1 tall...   
3    Conner has number0 dollars in his bank account...   
4    There are number0 dogwood trees currently in t...   
..                                                 ...   
379  There are number0 pencils and number1 crayons ...   
380  There are number0 pencils in the drawer . Sara...   
381  During a school play , Jonah staffed the snack...   
382  I have a pet golden retriever . Each year he g...   
383  Kaleb had saved up number0 dollars . If he rec...   

                                        Ques_Statement  \
0               how many books does he have in total ?   
1     How many chairs have been put out for the play ?   
2    How many short trees will the park have when t...   
3    How much money will Conner have in his account...   
4    How many dogwood trees will the park have when...   
..                                                 ...   
379           How many pencils are now in the drawer ?   
380            How many pencils are now there in all ?   
381  How many pitchers of lemonade did Jonah pour i...   
382                    How many pounds does he weigh ?   
383        how many number2 dollar toys could he buy ?   

                                                q_conv  \
0    Anderson took a look at his books as well . If...   
1    For the fifth grade play , the chairs have bee...   
2    There are 3730 short trees and 3731 tall trees...   
3    Anderson has 3730 dollars in his bank account ...   
4    There are 3730

**q_conv 변환**

In [542]:
def conv_question(q, data_set='mawps'):
    q = replace_numstr(q)
    tokens = nltk.tokenize.word_tokenize(q)
    tags = st.tag(tokens)
    name_list = []
    for tag in tags:
        if tag[1] == 'PERSON':
            if tag[0] not in name_list and tag[0] not in exception_word:
                name_list.append(tag[0])
        elif tag[0] in missing_word and tag[0] not in name_list:
            name_list.append(tag[0])
    #print(tags)
    for i, name in enumerate(name_list):
        q = q.replace(name, en_names[i])
    return q

In [543]:
for i, row in df.iterrows():
    #if i != 672:
        #continue
    df.loc[i, 'q_conv'] = conv_question(row['Question'])
    print(i)
    print(row['Question'])
    print(df.loc[i, 'q_conv'])

672
Mary ’ s mom is getting ready for Mary ’ s birthday party . She blew up number0 balloons this morning and number1 balloons this afternoon . How many balloons did she blow up in all ?
Anderson ’ s mom is getting ready for Anderson ’ s birthday party . She blew up 3730 balloons this morning and 3731 balloons this afternoon . How many balloons did she blow up in all ?


In [530]:
df

Question            Numbers  \
0     Mary is baking a cake . The recipe wants numbe...            8.0 2.0   
1     There are number0 erasers and number1 scissors...  139.0 118.0 131.0   
2     One pencil weighs number0 grams . How much do ...           28.3 5.0   
3     Zoe was unboxing some of her old winter clothe...        8.0 4.0 6.0   
4     Keith grew number0 cantelopes , Fred grew numb...     29.0 16.0 20.0   
...                                                 ...                ...   
1532  A worker at a medical lab is studying blood sa...  2.0 7341.0 4221.0   
1533  Carlos starts with number0 bananas . number1 a...           39.0 3.0   
1534  There are number0 scissors in the drawer . Kei...          54.0 22.0   
1535  In fourth grade there were number0 students at...     35.0 10.0 10.0   
1536  Third - grade students went to a concert in nu...           8.0 45.0   

                         Equation  Answer  \
0               - number0 number1     6.0   
1               + number0 number2   270.0   
2               * number0 number1   141.5   
3     * number0 + number1 number2    80.0   
4     + + number0 number1 number2    65.0   
...                           ...     ...   
1532            - number1 number2  3120.0   
1533            - number0 number1    36.0   
1534            + number0 number1    76.0   
1535  - + number0 number1 number1    35.0   
1536            * number0 number1   360.0   

                                            group_nums  \
0                   [8, 9, 10, 17, 18, 19, 26, 27, 28]   
1           [1, 2, 3, 4, 5, 6, 12, 13, 14, 24, 25, 26]   
2                       [2, 3, 4, 8, 9, 10, 9, 10, 11]   
3     [11, 12, 13, 21, 22, 23, 24, 25, 26, 35, 36, 37]   
4           [1, 2, 3, 6, 7, 8, 14, 15, 16, 23, 24, 25]   
...                                                ...   
1532  [10, 11, 12, 16, 17, 18, 24, 25, 26, 35, 36, 37]   
1533                    [2, 3, 4, 5, 6, 7, 17, 18, 19]   
1534                  [1, 2, 3, 9, 10, 11, 24, 25, 26]   
1535     [4, 5, 6, 16, 17, 18, 20, 21, 22, 35, 36, 37]   
1536                [8, 9, 10, 14, 15, 16, 22, 23, 24]   

                                                   Body  \
0     Mary is baking a cake . The recipe wants numbe...   
1     There are number0 erasers and number1 scissors...   
2                     One pencil weighs number0 grams .   
3     Zoe was unboxing some of her old winter clothe...   
4     Keith grew number0 cantelopes , Fred grew numb...   
...                                                 ...   
1532  A worker at a medical lab is studying blood sa...   
1533  Carlos starts with number0 bananas . number1 a...   
1534  There are number0 scissors in the drawer . Kei...   
1535  In fourth grade there were number0 students at...   
1536  Third - grade students went to a concert in nu...   

                                         Ques_Statement  \
0                  How many cups does she need to add ?   
1             How many erasers are now there in total ?   
2                   How much do number1 pencils weigh ?   
3     How many pieces of winter clothing did Zoe hav...   
4          How many cantelopes did they grow in total ?   
...                                                 ...   
1532   How many blood cells were in the second sample ?   
1533            How many bananas does Carlos end with ?   
1534           How many scissors are now there in all ?   
1535  How many students were in fourth grade at the ...   
1536            How many students went to the concert ?   

                                                 q_conv  q_papago  q_ko  \
0     Anderson is baking a cake . The recipe wants 3...       NaN   NaN   
1     There are 3730 erasers and 3731 scissors in th...       NaN   NaN   
2     One pencil weighs 3730 grams . How much do 373...       NaN   NaN   
3     Anderson was unboxing some of her old winter c...       NaN   NaN   
4     Anderson grew 3730 cantelopes , Cyndia grew 37...       NaN   NaN   
... 

**Papago API**

In [220]:
# sample source from papago
import os
import sys
import urllib.request
client_id = "*****" # 개발자센터에서 발급받은 Client ID 값
client_secret = "******" # 개발자센터에서 발급받은 Client Secret 값
encText = urllib.parse.quote("반갑습니다")
data = "source=ko&target=en&text=" + encText
url = "https://openapi.naver.com/v1/papago/n2mt"
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request, data=data.encode("utf-8"))
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)


{"message":{"@type":"response","@service":"naverservice.nmt.proxy","@version":"1.0.0","result":{"srcLangType":"ko","tarLangType":"en","translatedText":"Nice to meet you.","engineType":"PRETRANS","pivot":null}}}


In [232]:
res = json.loads(response_body.decode('utf-8'))
res['message']['result']['translatedText']

'Nice to meet you.'

In [259]:
import os
import sys
import urllib.request
import json

def trans_papago(q):
    client_id = "******" # 개발자센터에서 발급받은 Client ID 값
    client_secret = "*******" # 개발자센터에서 발급받은 Client Secret 값
    encText = urllib.parse.quote(q)
    data = "source=en&target=ko&text=" + encText
    url = "https://openapi.naver.com/v1/papago/n2mt"
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id",client_id)
    request.add_header("X-Naver-Client-Secret",client_secret)
    response = urllib.request.urlopen(request, data=data.encode("utf-8"))
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        res = json.loads(response_body.decode('utf-8'))
        return res['message']['result']['translatedText']
    else:
        print("Error Code:" + rescode)
        return None

def trans_papago_paid(q):
    client_id = "******" # 개발자센터에서 발급받은 Client ID 값
    client_secret = "*******" # 개발자센터에서 발급받은 Client Secret 값
    encText = urllib.parse.quote(q)
    data = "source=en&target=ko&text=" + encText
    url = "https://naveropenapi.apigw.ntruss.com/nmt/v1/translation"
    request = urllib.request.Request(url)
    request.add_header("X-NCP-APIGW-API-KEY-ID",client_id)
    request.add_header("X-NCP-APIGW-API-KEY",client_secret)
    response = urllib.request.urlopen(request, data=data.encode("utf-8"))
    rescode = response.getcode()
    if(rescode==200):
        response_body = response.read()
        res = json.loads(response_body.decode('utf-8'))
        return res['message']['result']['translatedText']
    else:
        print("Error Code:" + rescode)
        return None

10000자 밖에 안되서 너무 짧음. crawling으로 해보자(실패). 유료계정 등록

In [264]:
type(row['q_papago'])

str

In [235]:
df['q_conv'][0]

'Brian took a look at his books as well . If Brian has 3730 books in each of his 3731 bookshelves , how many books does he have in total ?'

In [260]:
trans_papago_paid(df['q_conv'][0])

'앤더슨은 그의 책들 또한 살펴보았다. 만약 앤더슨이 그의 3731개의 책장들 각각에 3730권의 책을 가지고 있다면, 그는 총 몇권의 책을 가지고 있는가?'

In [545]:
for i, row in df.iterrows():
    #if not isinstance(row['q_papago'], str) and not np.isnan(row['q_papago']):
    if isinstance(row['q_papago'], str):
        continue
    df.loc[i, 'q_papago'] = trans_papago_paid(row['q_conv'])
    print(i)
    print(row['q_conv'])
    print(df.loc[i, 'q_papago'])

672
Anderson ’ s mom is getting ready for Anderson ’ s birthday party . She blew up 3730 balloons this morning and 3731 balloons this afternoon . How many balloons did she blow up in all ?
앤더슨의 엄마는 앤더슨의 생일 파티를 준비하고 있습니다. 그녀는 오늘 아침 3730개의 풍선을 불었고 오후에는 3731개의 풍선을 불었다. 그녀는 모두 몇 개의 풍선을 불었니?


```
Anderson sold 3730 boxes of Trefoils . How many cases of 3731 boxes , plus extra boxes does Anderson need to deliver ?
Anderson은 3730박스의 트레포일을 팔았다. 앤더슨이 배달해야 할 3731박스의 케이스와 추가 박스는 몇 개입니까?

(For Halloween)
For Anderson Cyndia and her sister combined the candy they received . Cyndia had 3730 pieces of candy while her sister had 3731 . If they ate 3732 pieces the first night , how many pieces do they have left ?
Anderson Cyndia와 그녀의 여동생이 그들이 받은 사탕을 합쳤습니다. Cyndia는 그녀의 여동생이 3731을 가진 동안 3730조각의 사탕을 가지고 있었습니다. 만약 그들이 첫 밤에 3732조각들을 먹었다면, 그들은 얼마나 많은 조각들을 가지고 있습니까?

381
During a school play , Anderson staffed the snack bar . He served 3730 pitcher of lemonade during the first intermission , 3731 pitcher during the second , and 3732 pitcher during the third . How many pitchers of lemonade did Anderson pour in all ?
학교 연극동안, Anderson은 스낵바에 스탭을 달았습니다. 그는 첫 번째 중간 휴식 동안에 레모네이드의 3730 투수를, 두 번째 동안 3731 투수와 세 번째 동안 3732 투수를 위하여 봉사하였습니다. 앤더슨은 레모네이드를 모두 얼마나 많이 넣었는가?


오번역:  
Anderson was organizing her book case making sure each of the shelves had exactly 3730 books on it . If she had 3731 shelves of mystery books and 3732 shelves of picture books , how many books did she have total ?

만약 그녀가 3731개의 미스터리 책꽂이와 3732개의 그림책꽂이를 가지고 있다면, Anderson은 그녀의 책꽂이 각각 정확히 3730개의 책꽂이들이 그것의 위에 정확히 3730개의 책을 가지고 있었다면, 그녀는 총 몇권의 책을 가지고 있었습니까?

앤더슨은 책꽂이에 정확히 3730개의 책이 있도록 책장을 정리하고 있었습니다. 만약 그녀가 미스터리 서적으로 3731개의 책꽂이와 그림책으로 3732개의 책꽃이를 가지고 있다면, 그녀는 총 몇권의 책을 가지고 있었습니까?


```

In [799]:
# mawps fold0 train.csv
if df.loc[48,  'Question'] == "Nancy was organizing her book case making sure each of the shelves had exactly number0 books on it . If she had number1 shelves of mystery books and number2 shelves of picture books , how many books did she have total ?":
    df.loc[48, 'q_papago'] = '앤더슨은 책꽂이에 정확히 3730개의 책이 있도록 책장을 정리하고 있었습니다. 만약 그녀가 미스터리 서적으로 3731개의 책꽂이와 그림책으로 3732개의 책꽃이를 가지고 있다면, 그녀는 총 몇권의 책을 가지고 있었습니까?'
    
if df.loc[314, 'Question'] == "Rachel was organizing her book case making sure each of the shelves had exactly number0 books on it . If she had number1 shelves of mystery books and number2 shelves of picture books , how many books did she have total ?":
    df.loc[314, 'q_papago'] = '앤더슨은 책꽂이에 정확히 3730개의 책이 있도록 책장을 정리하고 있었습니다. 만약 그녀가 미스터리 서적으로 3731개의 책꽂이와 그림책으로 3732개의 책꽃이를 가지고 있다면, 그녀는 총 몇권의 책을 가지고 있었습니까?'
'''
if df.loc[471, 'Question'] == "Bianca was organizing her book case making sure each of the shelves had exactly number0 books on it . If she had number1 shelves of mystery books and number2 shelves of picture books , how many books did she have total ?":
    df.loc[471, 'q_papago'] = '앤더슨은 책꽂이에 정확히 3730개의 책이 있도록 책장을 정리하고 있었습니다. 만약 그녀가 미스터리 서적으로 3731개의 책꽂이와 그림책으로 3732개의 책꽃이를 가지고 있다면, 그녀는 총 몇권의 책을 가지고 있었습니까?'
    
if df.loc[1159,'Question'] == "Chloe was organizing her book case making sure each of the shelves had exactly number0 books on it . If she had number1 shelves of mystery books and number2 shelves of picture books , how many books did she have total ?":
    df.loc[1159, 'q_papago'] = '앤더슨은 책꽂이에 정확히 3730개의 책이 있도록 책장을 정리하고 있었습니다. 만약 그녀가 미스터리 서적으로 3731개의 책꽂이와 그림책으로 3732개의 책꽃이를 가지고 있다면, 그녀는 총 몇권의 책을 가지고 있었습니까?'

if df.loc[1093,'Question'] == "There were a total of number0 football games this year , number1 are played at night . Keith missed number2 of the games . How many football games did Keith go to in total ?":
    df.loc[1093, 'q_papago'] =  "올해에 총 3730개의 축구경기가 있었는데, 3731개는 밤에 경기됩니다. 앤더슨은 3732개의 경기들을 놓쳤습니다. 앤더슨은 총 몇 개의 축구 경기를 보러 갔습니까?"
    
if df.loc[758,'Question'] == "Dalton wants to buy a jump rope that costs $ number0 , a board game that costs $ number1 , and a playground ball that costs $ number2 . He has saved $ number3 from his allowance , and his uncle gave him $ number4 . How much more money does Dalton need to buy the jump rope , the game , and the ball ?":
    df.loc[758, 'q_papago'] = "앤더슨은 3730달러인 줄넘기, 3731달러인 보드게임, 그리고 3732달러인 운동장 공을 사고 싶어한다. 그는 그의 용돈으로부터 3733달러를 절약했고 그의 삼촌은 그에게 3734달러를 주었다. 줄넘기, 게임, 그리고 공을 사기 위해 앤더슨은 얼마나 더 많은 돈이 필요한가?"

# mawps fold0 dev.csv
if df.loc[43,  'Question'] == "Gwen was organizing her book case making sure each of the shelves had exactly number0 books on it . If she had number1 shelves of mystery books and number2 shelves of picture books , how many books did she have total ?":
    df.loc[43, 'q_papago'] = '앤더슨은 책꽂이에 정확히 3730개의 책이 있도록 책장을 정리하고 있었습니다. 만약 그녀가 미스터리 서적으로 3731개의 책꽂이와 그림책으로 3732개의 책꽃이를 가지고 있다면, 그녀는 총 몇권의 책을 가지고 있었습니까?'
if df.loc[105,  'Question'] == "Gwen was organizing her book case making sure each of the shelves had exactly number0 books on it . If she had number1 shelves of mystery books and number2 shelves of picture books , how many books did she have total ?":
    df.loc[105, 'q_papago'] = '앤더슨은 책꽂이에 정확히 3730개의 책이 있도록 책장을 정리하고 있었습니다. 만약 그녀가 미스터리 서적으로 3731개의 책꽂이와 그림책으로 3732개의 책꽃이를 가지고 있다면, 그녀는 총 몇권의 책을 가지고 있었습니까?'
if df.loc[106,  'Question'] == "Megan was organizing her book case making sure each of the shelves had exactly number0 books on it . If she had number1 shelves of mystery books and number2 shelves of picture books , how many books did she have total ?":
    df.loc[106, 'q_papago'] = '앤더슨은 책꽂이에 정확히 3730개의 책이 있도록 책장을 정리하고 있었습니다. 만약 그녀가 미스터리 서적으로 3731개의 책꽂이와 그림책으로 3732개의 책꽃이를 가지고 있다면, 그녀는 총 몇권의 책을 가지고 있었습니까?'
'''    
    
trans_list = [
    (
    "A new building needed number0 windows . The builder had already installed number1 of them . If it takes number2 hours to install each window , how long will it take him to install the rest ?",
    "새 건물은 3730개의 창문이 필요했다. 건축업자는 이미 3731개의 창문을 설치했다. 만약 건축업자가 각각의 창문을 설치하는 데 3732시간이 걸린다면, 그가 나머지를 설치하는 데 얼마나 걸릴까?"
    ),   
    (
    "A magician was selling magic card decks for number0 dollars each . If he started with number1 decks and by the end of the day he had number2 left , how much money did he earn ?",
    "마술사가 마술카드를 한갑에 3730 달러에 팔고있다. 만약 마술사가 3731갑으로 시작해서 3732갑을 남겼다면, 그는 얼마의 돈을 벌었을까?"
    ),
    (
    "The school cafeteria had number0 apples . If they used number1 to make lunch for the students and then bought number2 more , how many apples would they have ?",
    "학교식당에는 3730개의 사과가 있었다. 만약 식당이 학생들을 위해 3731개로 점심을 만들고 3732개를 더 산다면, 그들은 얼마나 많은 사과를 가지고 있을까?"
    ),
    (
    "There are number0 students in the class and number1 pencils . If the pencils are divided equally among the students , how many does each student get ?",
    "학급에 3730명의 학생들과 3731개의 연필이 있다. 만약 연필이 학생들 사이에 똑같이 나눈다면, 각 학생은 몇개의 연필을 받는가?"
    ),
    (
    "There were number0 pieces of candy in a jar . If number1 pieces were red and the rest were blue , how many were blue ?",
    "단지안에 3730개의 사탕이 있다. 만약 3731개가 빨간색이고 나머지는 파란색이라면, 얼마나 많은 조각들이 파란색인가?"
    ),
    (
    "A marine biologist measured number0 fish that was number1 foot long and a second fish that was number2 foot long . How much longer was the first fish ?",
    "어느 해양 생물학자가 3731피트 길이의 3730마리의 물고기를 측정했다. 그리고 3732피트 길이의 두 번째 물고기를 측정했다. 첫 번째 물고기의 길이는 얼마인가?"
    ),
    (
    "A cell phone company has a total of number0 customers across the world . If number1 of its customers live in the United States , how many of its customers live in other countries ?",
    "어느 휴대폰 회사의 고객은 전세계에 3730명이다. 만약 고객중 3731명이 미국에 산다면, 다른 나라에는 몇명이 사는가?"
    ),
    (
    "There are number0 students in the class and number1 apples . If the apples are divided equally among the students , how many does each student get ?",
    "학급에 3730명의 학생들과 3731개의 사과가 있다. 만약 사과를 학생들 사이에 똑같이 나눈다면, 각 학생은 몇개의 사과를 받는가?"
    ),
    (
    "There are number0 students in the class and number1 tickets . If the tickets are divided equally among the students , how many does each student get ?",
    "학급에 3730명의 학생들과 3731개의 티켓이 있다. 만약 티켓을 학생들 사이에 똑같이 나눈다면, 각 학생은 몇개의 티켓을 받는가?"
    ),
    (
    "There are number0 students in the class and number1 eggs . If the eggs are divided equally among the students , how many does each student get ?",
    "학급에 3730명의 학생들과 3731개의 계란이 있다. 만약 계란을 학생들 사이에 똑같이 나눈다면, 각 학생은 몇개의 계란을 받는가?"
    ),
    (
    "For his car , Mike spent $ number0 on speakers and $ number1 on new tires . Mike wanted number2 CD 's for $ number3 but decided not to . In total , how much did Mike spend on car parts ?",
    "마이크는 차에 사용하려고 3730달러의 스피커와 3731달러의 새 타이어를 샀다. 앤더슨은 3733달러에 3732 CD를 사고 싶었지만 그러지 않기로 결정했다. 앤더슨은 자동차 부품에 총 얼마를 썼는가?"
    ),
    (
    "When Joan was visited by the toothfairy , she received number0 each of quarters , half - dollars , and dimes . How much money did the toothfairy leave Joan ?",
    "이빨요정이 앤더슨을 찾아왔을 때, 그녀는 25센트, 50센트, 10센트짜리를 각각 3730개 받았습니다. 이빨요정은 앤더슨에게 모두 얼마의 돈을 주었는가?"
    ),
    (
    "A company painted some houses in Hancock County white and blue using a total of number0 gallons of paint . If they used number1 gallons of white paint , how many gallons of blue paint did the company use ?",
    "서울의 건설회사는 어떤 집을 칠하는데 3730리터의 흰색과 파란색의 페인트를 사용했다. 건설회사가 3731갤런의 흰 페인트를 사용했다면, 회사는 몇 리터의 파란 페인트를 사용했을까?"
    ),
    (
    "There are number0 candies in a pile on the desk . Each candy comes in a package of number1 . number2 candies are added to the pile . How many candies are there in the pile ?",
    "책상위에 3730개의 사탕이 있다. 사탕은 3731개씩 포장되어 있다. 책상에 3732개의 사탕을 더하면, 모두 몇개의 사탕이 있는가?"
    ),
    (
    "There are number0 apples in a pile on the desk . Each apple comes in a package of number1 . number2 apples are added to the pile . How many apples are there in the pile ?",
    "책상위에 3730개의 사과가 있다. 사과는 3731개씩 포장되어 있다. 책상에 3732개의 사과를 더하면, 모두 몇개의 사과가 있는가?"
    ),
    (
    "There are number0 bananas in a pile on the desk . Each banana comes in a package of number1 . number2 bananas are added to the pile . How many bananas are there in the pile ?",
    "책상위에 3730개의 바나나가 있다. 바나나는 3731개씩 포장되어 있다. 책상에 3732개의 바나나를 더하면, 모두 몇개의 바나나가 있는가?"
    ),
    (
    "The junior ranger asked Christian to help him place number0 seedlings in packets . If every packet needs to contain number1 seeds , how many packets do they need ?",
    "경비가 앤더슨에게 3730개의 묘목을 묶어달라고 했다. 만약 모든 묶음이 3731개의 씨앗을 포함할 필요가 있다면, 그들은 얼마나 많은 묶음을 필요로 할까?"
    ),
    (
    "In one year , for the election for president there were number0 million voters , whereas in the next year there were number1 million voters . Find the percentage change in the number of voters ?",
    "올해의 선거를 위한 유권자가 3730만명 이다. 내년에는 3731만명의 유권자가 될 것이다. 유권자의 증가율을 백분율로 계산하면 얼마인가?"
    ),
    (
    "On Friday , number0 people visited the zoo . number1 times as many people visited on Saturday than on Friday . How many people visited the zoo on Saturday ?",
    "금요일에 3730명의 사람들이 동물원을 방문하였다. 토요일에는 금요일보다 3731배 많은 사람들이 방문하였다. 토요일에는 몇 명이 동물원을 방문하였는가?"
    ),
    (
    "A pet shelter had number0 puppies when another number1 were brought in . If number2 puppies a day are adopted , how long would it take for all of them to be adopted ?",
    "애완동물 보호소에는 3730마리의 강아지들이 있었는데, 3731강아지들이 더 입양되었다. 만약 3732마리의 강아지들이 하루에 입양된다면, 모두가 입양될 때까지 몇일이나 걸릴까?"
    ),
]

for i, row in df.iterrows():
    q_o = row['Question']
    for org, trans in trans_list:
        if org in q_o:
            df.loc[i, 'q_papago'] = trans


In [697]:
df.loc[758, 'q_papago']

'앤더슨은 3730달러인 줄넘기, 3731달러인 보드게임, 그리고 3732달러인 운동장 공을 사고 싶어한다. 그는 그의 용돈으로부터 3733달러를 절약했고 그의 삼촌은 그에게 3734달러를 주었다. 줄넘기, 게임, 그리고 공을 사기 위해 앤더슨은 얼마나 더 많은 돈이 필요한가?'

**번역 확인**

In [800]:
# number 수 비교
for i, row in df.iterrows():
    q_o = row['Question']
    q_p = row['q_papago']
    match1_list = re.findall('number(\\d+)', q_o)
    match2_list = re.findall('373(\\d+)', q_p)
    if len(match1_list) != len(match2_list):
        print(i)
        print('"'+q_o+'",')
        print('"'+q_p+'"')

In [570]:
# 두 단어 이름(First name, last name) ==> Halloween 예외 처리
for i, row in df.iterrows():
    q_p = row['q_papago']
    flag = 0
    l = len(en_names)
    for j in range(l-1):
        full_name = en_names[j] + ' ' + en_names[j+1]
        if full_name in q_p:
            flag = 1
    if flag == 1:
        print(i)
        print(row['Question'])
        print(row['q_conv'])
        print(q_p)

In [316]:
df.loc[140, 'q_papago'] 

'할로윈을 위해 앤더슨과 그녀의 여동생은 그들이 받은 사탕을 합쳤습니다. 앤더슨은 그녀의 여동생이 3731을 가진 동안 3730조각의 사탕을 가지고 있었습니다. 만약 그들이 첫번째 밤에 3732조각들을 먹었다면, 그들은 얼마나 많은 조각들을 가지고 있습니까?'

In [547]:
for i, row in df.iterrows():
    print(row['q_papago'])

Anderson은 케이크를 굽고 있다. 그 요리법은 3730컵의 밀가루를 원한다. 그녀는 이미 3731개의 컵을 넣었다. 그녀는 몇 개의 컵을 추가해야 합니까?
3730개의 지우개와 3731개의 가위가 서랍안에 있다. 앤더슨은 3732개의 지우개를 서랍안에 놓았다. 현재 지우개가 총 몇 개 있습니까?
연필 한 자루의 무게는 3730그램이다. 3731개의 연필은 무게가 얼마나 나갑니까?
Anderson은 그녀의 오래된 겨울 옷들 중 일부를 풀고 있었다. 그녀는 3730개의 옷상자를 발견했고 각각의 상자 안에는 3731개의 스카프와 3732개의 벙어리장갑이 있었다. 앤더슨은 겨울옷의 총 몇 조각을 가지고 있었는가?
앤더슨은 3730개의 칸텔로프를, 신디아는 3731개의 칸텔로프를, 프레드는 3732개의 칸텔로프를 키웠습니다. 그들은 총 몇 개의 캉텔로프를 키웠나요?
앤더슨은 사모아 3730박스를 팔았다. 앤더슨은 3731박스의 케이스와 여분의 박스가 몇 개나 필요합니까?
앤더슨은 3730개의 블록을 가지고 있다. 신디아는 3731개의 블록을 가지고 있다. 신디아는 또 다른 3732개의 블록을 찾는다. 신디아는 몇개의 블록으로 끝납니까?
앤더슨은 꽃다발을 만들기 위해 3730개의 튤립과 3731개의 장미를 골랐다. 만약 그녀가 단지 3732개의 꽃을 사용했다면, 앤더슨은 얼마나 많은 여분의 꽃을 골랐는가?
앤더슨은 3730인치의 흰색 선을 그었다. 그리고 그는 3731인치 길이의 파란 선을 그었다. 흰색 줄이 파란색 줄보다 얼마나 길었나요?
앤더슨은 시속 3731마일로 3730마일을 비행했다. 앤더슨은 얼마나 오래 비행했습니까?
3731명의 더 많은 선수들이 게임에 참여했을 때, 3730명의 친구들이 온라인으로 비디오 게임을 하고 있었다. 만약 각 선수가 3732명의 생명을 가졌다면, 그들은 총 몇명의 생명을 가졌는가?
Anderson은 카페테리아 일꾼들이 점심 쟁반을 집는 것을 돕고 있었습니다, 그러나 그는 한 번에 3730개의 쟁반만 운반할 수 있었습니다. 만약

In [548]:
# 영문 미번역 이름 확인
for i, row in df.iterrows():
    q_p = row['q_papago']
    flag = 0
    for en_name in en_names:
        if en_name in q_p:
            flag = 1
    if flag == 1:
        print(i)
        print(row['q_conv'])
        print(q_p)

0
Anderson is baking a cake . The recipe wants 3730 cups of flour . She already put in 3731 cups . How many cups does she need to add ?
Anderson은 케이크를 굽고 있다. 그 요리법은 3730컵의 밀가루를 원한다. 그녀는 이미 3731개의 컵을 넣었다. 그녀는 몇 개의 컵을 추가해야 합니까?
3
Anderson was unboxing some of her old winter clothes . She found 3730 boxes of clothing and inside each box there were 3731 scarves and 3732 mittens . How many pieces of winter clothing did Anderson have total ?
Anderson은 그녀의 오래된 겨울 옷들 중 일부를 풀고 있었다. 그녀는 3730개의 옷상자를 발견했고 각각의 상자 안에는 3731개의 스카프와 3732개의 벙어리장갑이 있었다. 앤더슨은 겨울옷의 총 몇 조각을 가지고 있었는가?
11
Anderson was helping the cafeteria workers pick up lunch trays , but he could only carry 3730 trays at a time . If he had to pick up 3731 trays from one table and 3732 trays from another , how many trips will he make ?
Anderson은 카페테리아 일꾼들이 점심 쟁반을 집는 것을 돕고 있었습니다, 그러나 그는 한 번에 3730개의 쟁반만 운반할 수 있었습니다. 만약 그가 한 테이블로부터 3731개의 트레이와 다른 테이블로부터 3732개의 트레이를 집어야 한다면, 그는 얼마나 많은 여행을 할 것인가?
24
Anderson went to a pet shop . He bought 3730 go

**번역 수정**

**q_p 복사**

In [801]:
df['q_ko'] = df['q_papago']

**영문 미번역 이름 변환**

In [802]:
# 영문 미번역 이름 변환
for i, row in df.iterrows():
    q_p = row['q_ko']
    flag = 0
    for k, en_name in enumerate(en_names):
        if en_name in q_p:
            q_p = q_p.replace(en_name, ko_names[k])
            df.loc[i, 'q_ko'] = q_p
            flag = 1
    if flag == 1:
        print(i)
        print(q_p)

11
앤더슨은 케이크를 굽고 있다. 그 요리법은 3730컵의 밀가루와 3731컵의 설탕을 요구한다. 그녀는 이미 3732컵의 밀가루를 넣었다. 그녀는 몇 컵의 밀가루를 넣어야 합니까?
12
앤더슨은 두권의 색칠책을 샀다. 하나는 3730장의 사진을 가지고 있었고 다른 하나는 3731장의 사진을 가지고 있었다. 일주일 후에 그녀는 이미 3732장의 사진을 색칠했다. 그녀는 아직도 몇 장의 그림을 색칠해야 합니까?
13
앤더슨은 3730개의 사과를 가지고 있습니다. 신디아는 앤더슨 3731을 더 줍니다. 나중에, 앤더슨은 가게에서 3732개의 티켓을 삽니다. 앤더슨은 모두 몇 개의 사과를 가지고 있습니까?
26
앤더슨은 카페테리아 일꾼들이 점심 쟁반을 집는 것을 돕고 있었습니다, 그러나 그는 한 번에 3730개의 쟁반만 운반할 수 있었습니다. 만약 그가 한 테이블로부터 3731개의 트레이와 다른 테이블로부터 3732개의 트레이를 집어야 한다면, 그는 얼마나 많은 여행을 할 것인가?
38
앤더슨은 그녀의 오래된 겨울 옷들 중 일부를 풀고 있었다. 그녀는 3730개의 옷상자를 발견했고 각각의 상자 안에는 3731개의 스카프와 3732개의 벙어리장갑이 있었다. 앤더슨은 겨울옷의 총 몇 조각을 가지고 있었는가?
107
앤더슨은 3730컵의 호두를 trail mix의 한 묶음에 더했습니다. 나중에, 그녀는 3731컵의 아몬드를 더했습니다. 앤더슨은 총 몇 컵의 견과류를 트레일에 섞었는가?
145
마을 카니발에서 앤더슨은 관람차를 3730번, 범퍼카는 3731번 탔다. 만약 각각의 놀이기구가 3732번이라면, 그는 얼마나 많은 표를 사용하였는가?
187
앤더슨은 옷을 사기 위해 쇼핑몰에 갔다. 그녀는 반바지에 3730달러, 셔츠에 3731달러, 재킷에 3732달러를 썼다. 앤더슨은 얼마나 많은 돈을 옷에 썼습니까?
204
한 상자에는 3730개의 연필이 있다. 앤더슨은 3731개의 연필을 가지고 간다. 몇 개가 남았니?
212
상자안에 각각의 초콜릿 바는 3730달러입니다.

In [573]:
new_ko_names      = [ '지훈', '민우', '윤재', '정현', '유나', '지현', '지민', '서희']
new_ko_names_flag = [     1,     0,     0,    1,     0,     1,     1,     0]
josa_list         = [  '는', '은', '가', '이', '와', '과' ]

In [574]:
import random
def convert_new_ko_name(q):
#q = test_string
    idx_list = list(range(len(new_ko_names)))
    random.shuffle(idx_list)
    for ko_name in ko_names:
        if ko_name in q:
            idx = idx_list.pop()
            new_ko_name = new_ko_names[idx]
            flag = new_ko_names_flag[idx]
            for i, josa in enumerate(josa_list):
                new_josa = josa_list[(i//2)*2 + flag]
                q = q.replace(ko_name+josa, new_ko_name+new_josa)
            q = q.replace(ko_name, new_ko_name)
    return q

In [422]:
test_string = "앤더슨은 앤더슨이 앤더슨과 앤더슨, 신디아는 신디아가 신디아와 신디아"
convert_new_ko_name(test_string)

In [803]:
# 한국 이름 치환, number 치환
for i, row in df.iterrows():
    q = row['q_ko']
    q = convert_new_ko_name(q)
    q = restore_numstr(q)
    q = q.replace('  ', ' ')
    q = q.replace('.', ' .')
    q = q.replace('  ', ' ')
    q = q.replace(',', ' ,')
    q = q.replace('  ', ' ')
    q = q.replace('?', ' ?')
    q = q.replace('  ', ' ')
    df.loc[i, 'q_ko'] = q

In [645]:
df['q_ko']

0      지현은 그의 책들 또한 살펴보았다 . 만약 지현이 그의 number1개의 책장들 각...
1      5학년 연극을 위하여 , 의자들은 number1개의 의자와 함께 number0개의 ...
2      공원에는 현재 number0그루의 짧은 나무와 number1그루의 높은 나무가 있다...
3      민우는 그의 은행 계좌에 number0달러를 가지고 있다 . 매달 그는 number...
4      현재 공원에는 number0그루의 개나무가 있다 . 공원 일꾼들은 number1그루...
                             ...                        
379    서랍에는 number0개의 연필과 number1개의 크레용이 있다 . 지현은 num...
380    number0개의 연필이 서랍안에 있다 . 윤재는 number1개의 연필을 더 서랍...
381    학교 연극동안 , 지현은 스낵바에 스탭을 달았습니다 . 그는 첫 번째 중간 휴식 동...
382    나는 애완용 골든 리트리버를 가지고 있다 . 매년 그는 number0파운드를 번다 ...
383    지민은 number0달러를 저축했었다 . 만약 그가 그의 용돈으로 number1달러...
Name: q_ko, Length: 384, dtype: object

**group_num**

In [804]:
def isnot_punc(word):
    return word not in ['.', ',', '?']

for idx, row in df.iterrows():
    q = row['q_ko']
    words = q.split(' ')
    n = len(words)
    group_num = []
    for i, word in enumerate(words):
        if 'number' in word:
            for j in range(i-1, -1, -1):
                if isnot_punc(word):
                    if j not in group_num:
                        group_num.append(j)
                    break
            if i not in group_num:
                group_num.append(i)
            for j in range(i+1, n):
                if isnot_punc(word):
                    if j not in group_num:
                        group_num.append(j)
                    break
    last_num = 0
    
    '''
    for i in range(n-3, -1, -1):
        if isnot_punc(words[i]):
            last_num += 1
            if i not in group_num:
                group_num.append(i)
            if last_num >= 3:
                break
    '''
    for i in range(n-2, -1, -1):
        last_num += 1
        group_num.append(i)
        if last_num >= 3:
            break
    group_num.sort()
    df.loc[idx, 'group_nums_ko'] = '%s'%group_num
    #print(q)
    #group_str = [words[i] for i in group_num]
    #print(' '.join(group_str))
    #print(group_num)
    #print(len(words))
    
    #print(words)
        
                

In [778]:
df

Question            Numbers  \
0     Mary is baking a cake . The recipe wants numbe...            8.0 2.0   
1     There are number0 erasers and number1 scissors...  139.0 118.0 131.0   
2     One pencil weighs number0 grams . How much do ...           28.3 5.0   
3     Zoe was unboxing some of her old winter clothe...        8.0 4.0 6.0   
4     Keith grew number0 cantelopes , Fred grew numb...     29.0 16.0 20.0   
...                                                 ...                ...   
1532  A worker at a medical lab is studying blood sa...  2.0 7341.0 4221.0   
1533  Carlos starts with number0 bananas . number1 a...           39.0 3.0   
1534  There are number0 scissors in the drawer . Kei...          54.0 22.0   
1535  In fourth grade there were number0 students at...     35.0 10.0 10.0   
1536  Third - grade students went to a concert in nu...           8.0 45.0   

                         Equation  Answer  \
0               - number0 number1     6.0   
1               + number0 number2   270.0   
2               * number0 number1   141.5   
3     * number0 + number1 number2    80.0   
4     + + number0 number1 number2    65.0   
...                           ...     ...   
1532            - number1 number2  3120.0   
1533            - number0 number1    36.0   
1534            + number0 number1    76.0   
1535  - + number0 number1 number1    35.0   
1536            * number0 number1   360.0   

                                            group_nums  \
0                   [8, 9, 10, 17, 18, 19, 26, 27, 28]   
1           [1, 2, 3, 4, 5, 6, 12, 13, 14, 24, 25, 26]   
2                       [2, 3, 4, 8, 9, 10, 9, 10, 11]   
3     [11, 12, 13, 21, 22, 23, 24, 25, 26, 35, 36, 37]   
4           [1, 2, 3, 6, 7, 8, 14, 15, 16, 23, 24, 25]   
...                                                ...   
1532  [10, 11, 12, 16, 17, 18, 24, 25, 26, 35, 36, 37]   
1533                    [2, 3, 4, 5, 6, 7, 17, 18, 19]   
1534                  [1, 2, 3, 9, 10, 11, 24, 25, 26]   
1535     [4, 5, 6, 16, 17, 18, 20, 21, 22, 35, 36, 37]   
1536                [8, 9, 10, 14, 15, 16, 22, 23, 24]   

                                                   Body  \
0     Mary is baking a cake . The recipe wants numbe...   
1     There are number0 erasers and number1 scissors...   
2                     One pencil weighs number0 grams .   
3     Zoe was unboxing some of her old winter clothe...   
4     Keith grew number0 cantelopes , Fred grew numb...   
...                                                 ...   
1532  A worker at a medical lab is studying blood sa...   
1533  Carlos starts with number0 bananas . number1 a...   
1534  There are number0 scissors in the drawer . Kei...   
1535  In fourth grade there were number0 students at...   
1536  Third - grade students went to a concert in nu...   

                                         Ques_Statement  \
0                  How many cups does she need to add ?   
1             How many erasers are now there in total ?   
2                   How much do number1 pencils weigh ?   
3     How many pieces of winter clothing did Zoe hav...   
4          How many cantelopes did they grow in total ?   
...                                                 ...   
1532   How many blood cells were in the second sample ?   
1533            How many bananas does Carlos end with ?   
1534           How many scissors are now there in all ?   
1535  How many students were in fourth grade at the ...   
1536            How many students went to the concert ?   

                                                 q_conv  \
0     Anderson is baking a cake . The recipe wants 3...   
1     There are 3730 erasers and 3731 scissors in th...   
2     One pencil weighs 3730 grams . How much do 373...   
3     Anderson was unboxing some of her old winter c...   
4     Anderson grew 3730 cantelopes , Cyndia grew 37...   
...                                                 ...   
1532  A worker at a medical lab is studyi

In [779]:
a = [0, 1, 2]

In [780]:
'%s'%a

'[0, 1, 2]'

**Save CSV**

In [805]:
kor_path, trans_path

('/home/kotech/workspace/SVAMP/code/graph2tree/data/cv_mawps/fold0/dev-ko.csv',
 '/home/kotech/workspace/SVAMP/code/graph2tree/data/cv_mawps/fold0/dev-trans.csv')

In [806]:
df.to_csv(trans_path, index=False)

In [2]:
df_ko = pd.read_csv(trans_path)
df_ko

NameError: name 'pd' is not defined

In [808]:
df_ko['Question'] = df_ko['q_ko']
df_ko['group_nums'] = df_ko['group_nums_ko']

In [809]:
df_ko

Question  \
0    지민은 그의 책들 또한 살펴보았다 . 만약 지민이 그의 number1개의 책장들 각...   
1    5학년 연극을 위하여 , 의자들은 number1개의 의자와 함께 number0개의 ...   
2    공원에는 현재 number0그루의 짧은 나무와 number1그루의 높은 나무가 있다...   
3    정현은 그의 은행 계좌에 number0달러를 가지고 있다 . 매달 그는 number...   
4    현재 공원에는 number0그루의 개나무가 있다 . 공원 일꾼들은 number1그루...   
..                                                 ...   
379  서랍에는 number0개의 연필과 number1개의 크레용이 있다 . 유나는 num...   
380  number0개의 연필이 서랍안에 있다 . 유나는 number1개의 연필을 더 서랍...   
381  학교 연극동안 , 서희는 스낵바에 스탭을 달았습니다 . 그는 첫 번째 중간 휴식 동...   
382  나는 애완용 골든 리트리버를 가지고 있다 . 매년 그는 number0파운드를 번다 ...   
383  서희는 number0달러를 저축했었다 . 만약 그가 그의 용돈으로 number1달러...   

                          Numbers                     Equation        Answer  \
0                        56.0 9.0            * number0 number1    504.000000   
1                       27.0 16.0            * number0 number1    432.000000   
2                  41.0 44.0 57.0            + number0 number2     98.000000   
3              25000.0 1500.0 8.0  - number0 * number1 number2  13000.000000   
4                       34.0 49.0            + number0 number1     83.000000   
..                            ...                          ...           ...   
379                34.0 49.0 22.0            - number0 number2     12.000000   
380                   115.0 100.0            + number0 number1    215.000000   
381  0.25 0.4166666666666667 0.25  + + number0 number0 number1      0.916667   
382                      11.0 8.0            * number0 number1     88.000000   
383                 21.0 15.0 6.0  / + number0 number1 number2      6.000000   

                                           group_nums  \
0                  [8, 9, 10, 11, 12, 13, 20, 21, 22]   
1                      [4, 5, 6, 7, 8, 9, 15, 16, 17]   
2          [1, 2, 3, 4, 5, 6, 12, 13, 14, 26, 27, 28]   
3        [3, 4, 5, 9, 10, 11, 20, 21, 22, 27, 28, 29]   
4                      [1, 2, 3, 7, 8, 9, 19, 20, 21]   
..                                                ...   
379              [0, 1, 2, 3, 4, 7, 8, 9, 16, 17, 18]   
380                       [0, 1, 5, 6, 7, 15, 16, 17]   
381  [14, 15, 16, 20, 21, 22, 25, 26, 27, 34, 35, 36]   
382                [8, 9, 10, 12, 13, 14, 16, 17, 18]   
383        [0, 1, 2, 7, 8, 9, 12, 13, 14, 16, 17, 18]   

                                                  Body  \
0    Bryan took a look at his books as well . If Br...   
1    For the fifth grade play , the chairs have bee...   
2    There are number0 short trees and number1 tall...   
3    Conner has number0 dollars in his bank account...   
4    There are number0 dogwood trees currently in t...   
..                                                 ...   
379  There are number0 pencils and number1 crayons ...   
380  There are number0 pencils in the drawer . Sara...   
381  During a school play , Jonah staffed the snack...   
382  I have a pet golden retriever . Each year he g...   
383  Kaleb had saved up number0 dollars . If he rec...   

                                        Ques_Statement  \
0               how many books does he have in total ?   
1     How many chairs have been put out for the play ?   
2    How many short trees will the park have when t...   
3    How much money will Conner have in his account...   
4    How many dogwood trees will the park have when...   
..                                                 ...   
379           How many pencils are now in the drawer ?   
380            How many pencils are now there in all ?   
381  How many pitchers of lemonade did Jonah pour i...   
382                    How many pounds does he weigh ?   
383        how many number2 dollar toys could he buy ?   

                                                q_conv  \
0    Anderson took a look at his books as well . If...   
1    For the fifth grade play , the chairs have bee...   
2    There are 3730 short trees and 3731 tall trees...   
3    Anderson has 3730 dollars in his bank account ...   
4    There are 3730

In [1]:
df_ko[0, 'group_nums_ko']

NameError: name 'df_ko' is not defined

In [810]:
df_ko.to_csv(kor_path, index=False)

**오류확인**

In [673]:
for idx, row in df.iterrows():
    if idx > 20:
        break
    tokens = row['Question'].split()
    n = len(tokens)
    for i, token in enumerate(tokens):
        if 'number' in token:
            if i > 0 and (tokens[i-1] == '.' or tokens[i-1] == ','):
                print(i, row['Question'])
                print(row['group_nums'])
            if i < n-1 and (tokens[i+1] == '.' or tokens[i+1] == ','):
                print(i, row['Question'])
                

12 A chef needs to cook number0 potatoes . He has already cooked number1 . If each potato takes number2 minutes to cook , how long will it take him to cook the rest ?
[4, 5, 6, 11, 12, 13, 17, 18, 19, 30, 31, 32]
14 Rachel bought two coloring books . One had number0 pictures and the other had number1 . After one week she had already colored number2 of the pictures . How many pictures does she still have to color ?
[7, 8, 9, 13, 14, 15, 22, 23, 24, 34, 35, 36]


In [694]:
print(df.loc[758, 'q_conv'])
print(df.loc[758, 'q_papago'])
print(df.loc[758, 'Question'])

Anderson wants to buy a jump rope that costs $ 3730 , a board game that costs $ 3731 , and a playground ball that costs $ 3732 . He has saved $ 3733 from his allowance , and his uncle gave him $ 3734 . How much more money does Anderson need to buy the jump rope , the game , and the ball ?
앤더슨은 3730달러인 줄넘기, 3731달러인 보드게임, 그리고 3732달러인 운동장 공을 사고 싶어한다. 그는 그의 용돈으로부터 3733달러를 절약했고 그의 삼촌은 그에게 줄넘기, 게임, 그리고 공을 사기 위해 앤더슨이 얼마나 더 많은 돈이 필요한가?
Dalton wants to buy a jump rope that costs $ number0 , a board game that costs $ number1 , and a playground ball that costs $ number2 . He has saved $ number3 from his allowance , and his uncle gave him $ number4 . How much more money does Dalton need to buy the jump rope , the game , and the ball ?


In [714]:
print(df.loc[62, 'q_conv'])
print(df.loc[62, 'q_papago'])
print(df.loc[62, 'Question'])
print(df.loc[645, 'q_papago'])
print(df.loc[915, 'q_papago'])
print(df.loc[1059, 'q_papago'])
print(df.loc[1397, 'q_papago'])
print(df.loc[1445, 'q_papago'])


A pet shelter had 3730 puppies when another 3731 were brought in . If 3732 puppies a day are adopted , how long would it take for all of them to be adopted ?
만약 3732마리의 강아지들이 하루에 입양된다면, 애완동물 보호소는 3730마리의 강아지들을 가지고 있었습니까?
A pet shelter had number0 puppies when another number1 were brought in . If number2 puppies a day are adopted , how long would it take for all of them to be adopted ?
만약 3732마리의 강아지들이 하루에 입양된다면, 애완동물 보호소는 3730마리의 강아지들을 가지고 있었습니까?
만약 3732마리의 강아지들이 하루에 입양된다면, 애완동물 보호소는 3730마리의 강아지들을 가지고 있었습니까?
만약 3732마리의 강아지들이 하루에 입양된다면, 애완동물 보호소는 3730마리의 강아지들을 가지고 있었습니까?
만약 3732마리의 강아지들이 하루에 입양된다면, 애완동물 보호소는 3730마리의 강아지들을 가지고 있었습니까?
만약 3732마리의 강아지들이 하루에 입양된다면, 애완동물 보호소는 3730마리의 강아지들을 가지고 있었습니까?


In [727]:

print(df.loc[62, 'q_conv'])
print(df.loc[62, 'q_papago'])
print(df.loc[62, 'Question'])
print(df.loc[645, 'q_papago'])
print(df.loc[915, 'q_papago'])
print(df.loc[1059, 'q_papago'])
print(df.loc[1397, 'q_papago'])
print(df.loc[1445, 'q_papago'])

A pet shelter had 3730 puppies when another 3731 were brought in . If 3732 puppies a day are adopted , how long would it take for all of them to be adopted ?
애완동물 보호소에는 3730마리의 강아지들이 있었는데, 3731강아지들이 더 입양되었다. 만약 3732마리의 강아지들이 하루에 입양된다면, 모두가 입양될 때까지 몇일이나 걸릴까?
A pet shelter had number0 puppies when another number1 were brought in . If number2 puppies a day are adopted , how long would it take for all of them to be adopted ?
애완동물 보호소에는 3730마리의 강아지들이 있었는데, 3731강아지들이 더 입양되었다. 만약 3732마리의 강아지들이 하루에 입양된다면, 모두가 입양될 때까지 몇일이나 걸릴까?
애완동물 보호소에는 3730마리의 강아지들이 있었는데, 3731강아지들이 더 입양되었다. 만약 3732마리의 강아지들이 하루에 입양된다면, 모두가 입양될 때까지 몇일이나 걸릴까?
애완동물 보호소에는 3730마리의 강아지들이 있었는데, 3731강아지들이 더 입양되었다. 만약 3732마리의 강아지들이 하루에 입양된다면, 모두가 입양될 때까지 몇일이나 걸릴까?
애완동물 보호소에는 3730마리의 강아지들이 있었는데, 3731강아지들이 더 입양되었다. 만약 3732마리의 강아지들이 하루에 입양된다면, 모두가 입양될 때까지 몇일이나 걸릴까?
애완동물 보호소에는 3730마리의 강아지들이 있었는데, 3731강아지들이 더 입양되었다. 만약 3732마리의 강아지들이 하루에 입양된다면, 모두가 입양될 때까지 몇일이나 걸릴까?


In [758]:

print(df.loc[118, 'q_conv'])
print(df.loc[118, 'q_papago'])
print(df.loc[118, 'Question'])

There are 3730 candies in a pile on the desk . Each candy comes in a package of 3731 . 3732 candies are added to the pile . How many candies are there in the pile ?
3730개의 사탕이 책상위에 쌓여있다. 각각의 사탕은 3731.3732개의 사탕이 더해진다. 더미 안에 사탕이 몇 개 있습니까?
There are number0 candies in a pile on the desk . Each candy comes in a package of number1 . number2 candies are added to the pile . How many candies are there in the pile ?


In [759]:
df.loc[118]

Question          There are number0 candies in a pile on the des...
Numbers                                                6.0 15.0 4.0
Equation                                          + number0 number2
Answer                                                         10.0
group_nums            [1, 2, 3, 17, 18, 19, 19, 20, 21, 33, 34, 35]
Body              There are number0 candies in a pile on the des...
Ques_Statement             How many candies are there in the pile ?
q_conv            There are 3730 candies in a pile on the desk ....
q_papago          3730개의 사탕이 책상위에 쌓여있다. 각각의 사탕은 3731.3732개의 사탕이 ...
q_ko              number0개의 사탕이 책상위에 쌓여있다 . 각각의 사탕은 number1 .num...
group_nums_ko                        [0, 1, 6, 7, 8, 9, 15, 16, 17]
Name: 118, dtype: object